# -*- coding: utf-8 -*-
# vim: ft=yaml
---
kubernetes:
  rootuser: root
  rootgroup: root
  arch: ''
  dir:
    binary: /usr/local
    source: /tmp/kubernetes
  # Just here for testing
  added_in_defaults: defaults_value
  winner: defaults

  kubectl:
    version: 1.18.2
    config_file: /etc/default/kubectl.ini
    config: {}
    environ_file: /etc/default/kubectl.sh
    environ: []
    service: {}
    linux:
      altpriority: 0
      symlink: /usr/local/bin/kubectl
    pkg:
      name: kubectl
      use_upstream_repo: false
      use_upstream_binary: true
      use_upstream_source: false
      deps:
        - curl
      repo:
        humanname: kubernetes
        name: kubernetes
        comments:
          - installed by salt
        enabled: 1
        gpgcheck: 1
      binary:
        uri: https://storage.googleapis.com/kubernetes-release/release
        name: kubectl
        source: null   # set in map.jinja
        source_hash: 6ea8261b503c6c63d616878837dc70b758d4a3aeb9996ade8e83b51aedac9698
        trim_output: true
      source:
        name: kubernetes
        uri: https://github.com/kubernetes/kubectl/archive
        source: null
        source_hash: f13e2706e173ceed635b3be60bf929c400ed31165bd0ad16ff0dd103821494ec
        trim_output: true
        archive_suffix: tar.gz
        archive_format: tar
        enforce_toplevel: false
        options: '--strip-components=1'

  minikube:
    version: 1.9.2
    config_file: /etc/default/minikube.ini
    config: {}
    environ_file: /etc/default/minikube.sh
    environ: []
    service: {}
    check: egrep --color 'vmx|svm' /proc/cpuinfo
    linux:
      altpriority: 0
      symlink: /usr/local/bin/minikube
    vm_driver: none
    pkg:
      name: minikube
      use_upstream_repo: false
      use_upstream_binary: true
      use_upstream_source: false
      deps:
        - curl
      repo:
        humanname: kubernetes
        name: kubernetes
        comments:
          - installed by salt
        enabled: 1
        gpgcheck: 1
      binary:
        name: minikube
        uri: https://github.com/kubernetes/minikube/releases/download
        source: null       # see map.jinja
        source_hash: 3121f933bf8d608befb24628a045ce536658738c14618504ba46c92e656ea6b5
        trim_output: true
      source:
        name: minikube
        uri: https://github.com/kubernetes/minikube/archive
        source: null
        source_hash: f94465221ad1f402e18b3ecd701c12a50d23e841a80de26c7861e3ddc86f2075
        trim_output: true
        archive_suffix: tar.gz
        archive_format: tar
        enforce_toplevel: false
        options: --strip-components=1

  retry_option:
    # https://docs.saltstack.com/en/latest/ref/states/requisites.html#retrying-states
    attempts: 3
    until: true
    interval: 60
    splay: 10
